name: build-docker-image
on:
    push:
        branches: [production]

jobs:
    build:
        name: build-odoo-backup-aws-s3-image
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build & Publish image
              run: |
                  cd ${{ github.workspace }}
                  docker build -t ${{ vars.ODOO_IMAGE_TAG }} .
                  docker push ${{ vars.ODOO_IMAGE_TAG }}
